# Generated by Django 2.2.6 on 2019-10-28 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_creation_date2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='creation_date2',
        ),
    ]
