# Generated by Django 2.2.6 on 2019-10-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auction',
            field=models.IntegerField(default=0),
        ),
    ]
