# Generated by Django 2.2.6 on 2019-10-28 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_auction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='auction',
            new_name='on_auction',
        ),
    ]
